   language:
    — ruby
   rvm:
    — 2.5.0
   cache:
    — bundler

    addons:
    code_climate:
      repo_token: ce153aab62e07a956e644d2ef349c1b8968085554cc3fcfba9a33d7a80fa52e6

install:
  - bundle install

services:
  — postgresql

script:
  - bundle exec rubocop
  - bin/rails db:create
  - bin/rails db:migrate
  - bin/rails db:seed
  - bundle exec rspec spec

after_success:
  - bundle exec codeclimate-test-reporter
